version: 0.0
os: linux
files:
  - source: /
    destination: /var/www
hooks:
  BeforeInstall:
    - location: create-web-dir.sh
      timeout: 300
      runas: ubuntu #run as root
  AfterInstall:
    - location: set-permissions.sh
      timeout: 300
      runas: ubuntu #run as root
    - location: move-html-files.sh  # New script to change permissions
      timeout: 300
      runas: ubuntu # run as root
    - location: install-service.sh
      timeout: 300
      runas: ubuntu # Add this step to move HTML files to the static folder
